# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "88ee2e12fea367bda8bae4cf1a1e18cb"
name = "adaptive-deal-app"
handle = "adaptive-deal-app-6"
application_url = "https://weekends-venezuela-analyzed-vital.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-52b79549.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://weekends-venezuela-analyzed-vital.trycloudflare.com/auth/callback",
  "https://weekends-venezuela-analyzed-vital.trycloudflare.com/auth/shopify/callback",
  "https://weekends-venezuela-analyzed-vital.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
